### ISSUE TITLE
As a Webcomponent Consumer I want that the Ski Area web component uses the actual APIs in order to see all Lifts shared by the Open Data Hub and not only the LTS one.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-tourism-skiareas#33]

**Comment by RudiThoeni** [comment]
extended web component skiareas (https://webcomponents.opendatahub.bz.it/webcomponent/8282479b-dc13-5012-939f-7a0196348dca) now it shows also DSS data (here i display the kml files because the gps points are very low quality)

**Comment by RudiThoeni** [comment]
added parameter which cuts out false gps poins (gps point assigned to Zürich)
